import React from "react";

interface Props {
  summary: string;
  actions: string[];
  captions?: string[];
}

export const SummaryPanel: React.FC<Props> = ({ summary, actions, captions = [] }) => {
  const handleExport = () => {
    const timestamp = new Date().toISOString().slice(0, 19).replace(/:/g, "-");
    const content = `# Meeting Summary - ${timestamp}

## Summary
${summary || "(No summary available)"}

## Action Items
${actions.length > 0 ? actions.map((a, i) => `${i + 1}. ${a}`).join("\n") : "(No action items)"}

## Captions
${captions.length > 0 ? captions.map((c, i) => `${i + 1}. ${c}`).join("\n") : "(No captions available)"}

---
Generated by LimitlessMeet
`;

    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `meeting-summary-${timestamp}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <aside
      aria-label="Meeting summary and action items"
      style={{
        position: "fixed",
        top: 10,
        right: 10,
        background: "rgba(0,0,0,0.7)",
        color: "#fff",
        padding: 0,
        maxWidth: 520,
        minWidth: 240,
        fontSize: 14,
        zIndex: 2147483647,
        borderRadius: 8,
        boxShadow: "0 2px 12px #0008",
        display: "flex",
        flexDirection: "row",
        gap: 0,
        overflow: "hidden",
      }}
    >
      <section
        aria-label="Live summary"
        style={{
          flex: 1,
          minWidth: 0,
          padding: "12px 16px 12px 12px",
          borderRight: actions.length > 0 ? "1px solid #444" : undefined,
          background: "rgba(0,0,0,0.8)",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <h4 style={{ margin: "4px 0 8px", fontWeight: 600, fontSize: 15 }}>Live Summary</h4>
        <p style={{ whiteSpace: "pre-wrap", margin: 0 }}>{summary || "(building…)"}</p>
        <button
          onClick={handleExport}
          aria-label="Export meeting summary and captions"
          style={{
            marginTop: 8,
            background: "#333",
            color: "#fff",
            border: "none",
            borderRadius: 4,
            padding: "4px 8px",
            fontSize: 12,
            cursor: "pointer",
          }}
        >
          Export
        </button>
      </section>
      {actions.length > 0 && (
        <section
          aria-label="Action items"
          style={{
            flex: 1,
            minWidth: 0,
            padding: "12px 16px 12px 12px",
            background: "rgba(0,0,0,0.75)",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <h5 style={{ margin: "4px 0 8px", fontWeight: 600, fontSize: 15 }}>Action Items</h5>
          <ul style={{ paddingLeft: 18, margin: 0 }}>
            {actions.map((a, i) => (
              <li key={i}>{a}</li>
            ))}
          </ul>
        </section>
      )}
      <style>{`
        @media (max-width: 600px) {
          .limitlessmeet-summarypanel {
            flex-direction: column !important;
            min-width: 0 !important;
            max-width: 98vw !important;
          }
          .limitlessmeet-summarypanel section {
            border-right: none !important;
            border-bottom: 1px solid #444 !important;
          }
        }
      `}</style>
    </aside>
  );
};